woowa-techcamp-2021/deal-11

- server/app.js
- server/db/config.js
- server/db/create.js
- server/db/init.js
- server/db/modelCreate.js
- server/db/models/Category.js
- server/db/models/Product.js
- server/db/models/User.js
- server/routes/auth.js
- server/routes/index.js
- db 생성 스크립트 추가
- model query 자동화 코드 추가
- user, product, category 모델 추가
> Feature/server: db 자동화 & model 추가

- .gitignore
- client/.babelrc
- client/index.html
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/core/Component.js
- client/src/main.js
- client/src/scss/app.scss
- client/webpack.config.js
- Component 클래스 추가
- webpack, babel 환경 셋팅
> Feature/front: Component 클래스 추가 & webpack, babel 환경 셋팅

- client/package.json
- client/src/scss/app.scss
- client/src/scss/reset.scss
- dev용 scripts 추가 했습니다
- 'npm run build:dev'
- reset scss 파일 추가하고 적용시켰습니다.
- 바로 build해보시면 적용된 것 확인하실 수 있습니다
> Feature/front: dev용 script 추가, reset scss 적용

- .gitignore
- client/src/lib/router.js
- client/src/main.js
- client/src/pages/Home.js
- client/src/pages/MyInfo.js
- client/src/utils.js
- router 구현 완료 했습니다 #22 
- utils.js로 간단한 validation 함수를 import 해옵니다. (클래스 인지..)
- main.js에 간단한 동작 방법 주석과 코드로 작성되어 있으니 한번 확인해보시고 리뷰주세요 !
> Feature/front: router 구현 완료

- .gitignore
- server/app.js
- server/db/models/Product.js
- server/package-lock.json
- server/package.json
- server/routes/auth.js
- server/routes/index.js
- server/routes/product/index.js
- server/routes/product/utils.js
- server/routes/utils.js
- 상품 메인화면 접속 시 모든 상품 중 15개만 불러오도록 구현
- 상품 등록 시 여러가지 텍스트 정보와 이미지 등록 가능하도록 구현
> Feature/Server: product 메인 화면 api, product 등록 구현 완료

- client/src/core/Component.js
- client/src/pages/Home.js
- client/src/pages/MyInfo.js
- client/src/store/index.js
- Component 클래스에서 자식을 rerender하는 메서드를 추가하였습니다.
- 중앙 상태 store 객체를 Component 클래스의 속성에 추가하였습니다.
- Home.js example 코드 확인해보세요
> Feature/front: Component 메서드 추가 & store 추가

- server/db/models/Product.js
- server/db/models/User.js
- server/db/models/User_like_product.js
- server/package-lock.json
- server/routes/index.js
- User_like_product 테이블 추가
- Product 모델 price 컬럼 추가
> Feature/server: model fix

- client/index.html
- client/src/assets/account.svg
- client/src/assets/category.svg
- client/src/assets/location.svg
- client/src/assets/menu.svg
- client/src/core/Component.js
- client/src/lib/router.js
- client/src/main.js
- client/src/pages/Home.js
- client/src/scss/app.scss
- client/src/scss/home.scss
- client/src/scss/reset.scss
- client/src/store/index.js
- store 객체 전파 구조 변경했습니다
- component childrerender 함수 구조 잡았습니다
- main 컴포넌트 nav바 마크업 완료
- main 컴포넌트 +버튼 추가
> Feature/front: Component 클래스 수정 & main nav바 마크업

- server/routes/product/index.js
- #14 chatroom 관련, productId별 수정, 삭제를 제외한 라우터를 구현
> Feature Server: Product 라우터 쿼리 수정 및 카테고리, 유저, 상세보기 api 수정

- server/app.js
- server/routes/auth.js
- server/routes/product/index.js
- server/routes/utils.js
- runAsyncWrapper 함수를 사용하여 try...catch 로직 분리를 통해 미들웨어 내 코드 심플하게 변경
> Refactor Server: 서버 비동기 처리 async/await 사용하도록 변경, try/catch 로직 분리

- server/app.js
- server/db/index.js
- server/db/models/Location.js
- server/db/models/Product.js
- server/db/models/User.js
- server/routes/auth.js
- server/routes/product/index.js
- server/routes/utils.js
- DB 모델 Locations 추가
- Products 모델 수정(location_id)
- Users 모델 location_1_id, location_2_id 추가
- product 조회 쿼리 중간에 location_id를 가져오는 서브쿼리 추가
> Feature/Server: 동네에 따라 정확하게 상품을 가져오도록 쿼리 및 계산 로직 수정

- server/app.js
- server/db/category.js
- server/db/models/Product.js
- server/package-lock.json
- server/package.json
- server/routes/auth.js
- server/routes/location.js
- server/routes/product/image.js
- server/routes/product/index.js
- server/routes/query.js
- server/routes/utils.js
되게 많은 부분을 수정했는데.. 따로 정리하기는 어려울 것 같습니다.
커밋 최대한 잘게 쪼개서 푸쉬했으니 커밋 내용 확인하시면 좋을 것 같아요 ~
> Feature/server: refactor server & add 좋아요 기능

- server/app.js
- server/db/models/Chat_rooms.js
- server/db/models/Message.js
- server/package-lock.json
- server/package.json
- server/routes/chat/index.js
- server/routes/index.js
- server/routes/product/image.js
- server/routes/product/index.js
- server/routes/query.js
- server/routes/utils.js
커밋 확인 해주세요..
이번에 커밋 했다가 다시 수정한 내용이 조금 있어서 밑에서 부터 보시는게...
> Feature/server: 몇 가지 수정 & add 상품 정보 수정하기

- client/src/component/auth/SignIn.js
- client/src/component/auth/SignUp.js
- client/src/component/auth/index.js
- client/src/component/auth/utils.js
- client/src/component/category/index.js
- client/src/component/home/Modal.js
- client/src/component/home/ToggleMenu.js
- client/src/component/menu/MenuTab.js
- client/src/component/menu/index.js
- client/src/component/shared/Button.js
- client/src/component/shared/Input.js
- client/src/component/shared/NavBar.js
- client/src/core/Component.js
- client/src/main.js
- client/src/scss/auth.scss
- client/src/scss/button.scss
- client/src/scss/category.scss
- client/src/scss/input.scss
- client/src/scss/menu.scss
- client/src/scss/myinfo.scss
- client/src/scss/navbar.scss
- client/src/scss/reset.scss
- client/src/scss/signin.scss
- client/src/scss/signup.scss
- client/src/scss/size.scss
- client/src/scss/theme.scss
- client/src/store/index.js
- client/src/utils.js
Auth
- SignIn
- SignUp
- index(Default)
Category
- index
Menu
- ProductList
- MenuTab
Menu는 컴포넌트를 분리할 생각입니다. + 비동기 요청이 아직 마무리되지 않았습니다.
> Feature/Front: Auth 페이지, Category 페이지, Menu 페이지 추가했습니다. (Menu는 비동기요청 미완)

- client/src/component/auth/index.js
- client/src/lib/event.js
- client/src/lib/router.js
- client/src/main.js
기존에 redirect는 hash push가 되어서 무한루프에 빠지는 오류가 있었는데
replace state시켜서 무한으로 빠지는 점을 제외시켰습니다.
앞으로 라우트 컴포넌트가 렌더링 되기 이전에 검증해야할 점이 있다면 mounted에서 검증하시지 마시고
middleware를 넣어주세요 !
> Refactor/front: route redirect 메서드 추가 & event 모듈화

- client/src/component/auth/SignIn.js
- client/src/component/home/index.js
- client/src/component/move.js
- client/src/lib/router.js
- client/src/main.js
- client/src/scss/app.scss
왼쪽 오른쪽으로 이동 가능하도록 구현했습니다.
아래쪽 위쪽도 추가할 예정이구요.
그리고 이전에 auth로 접근하면 mount 되는 시점에 검증을 해서 애니메이션에 오류가 발생해가지고
auth mount에서 로그인 검증 코드 지우고, middleware에서 검증시키도록 변경했습니다.
> add: hash change animation

- server/routes/auth.js
- 입력값 없어도 그냥 요청이 보내지고 회원가입 되는 현상을 방지하려고 유효성 검증 코드 넣었습니다 !
> Fix/server: 회원가입 유효성 검증

- client/src/component/auth/SignUp.js
- client/src/component/home/Modal.js
- client/src/component/post/index.js
- client/src/component/shared/Button.js
- client/src/lib/api.js
- client/src/lib/router.js
- client/src/main.js
- client/src/scss/app.scss
- client/src/scss/category.scss
- client/src/scss/post.scss
- client/webpack.config.js
> Feature/front: post 마크업 완료

- server/routes/query.js
> Fix/server: 채팅방 상세보기 쿼리 수정

- server/app.js
- 세션에 내 정보가 저장되어있는지 (내가 로그인을 했는지)를 가져오는 middleware를 추가했습니다
> Feature/server: 최초 내 정보 가져오기

- server/app.js
- server/package-lock.json
- server/package.json
- server/routes/auth.js
- server/routes/chat/index.js
- server/routes/index.js
- server/routes/product/image.js
- server/routes/product/index.js
- server/routes/utils.js
- 조금 급하게 구현한거라 중간중간 오류가 있을 수 있으니 한번 리뷰 부탁드릴게요 !!!
> Fix/Server: jwt 방식으로 인증 변경

- chat-server/LICENSE
- chat-server/app.json
- chat-server/index.html
- chat-server/index.js
- chat-server/package-lock.json
- chat-server/package.json
- client/src/component/Chat/ChatBubbleList.js
- client/src/component/Chat/ChatDetail.js
- client/src/component/menu/ChatList.js
- client/src/component/menu/ProductList.js
- client/src/component/menu/index.js
- client/src/scss/chatdetail.scss
- socket.io 채팅 서버 추가되었고
- ChatList 관련 컴포넌트들 리팩토링 진행 했습니다.
- ChatList가 마운트 될때 데이터를 불러오도록 만들었습니다.
> add: add socket.io chat-server, refactor: refactor ChatList Component to use in Menu Page

- server/app.js
- server/routes/product/index.js
- server/routes/query.js
- 본인의 관심 목록을 가져올 수 있습니다 `/api/v1/product/like` **GET**
- 본인의 동네를 변경할 수 있습니다 `/myinfo` **PUT**
- body로 동네 한 개 이상을 보내야 합니다.
> Feature/server: 내 관심목록 가져오기, 동네 바꾸기

- server/routes/product/index.js
- server/routes/query.js
> Fix/server: pagiantion
